#!/bin/sh

#
# Sample post-finish hook for Paradeiser (called when a pomodoro ended). It
# displays a simple notification.
#
# TODO Add platform switch for Mac / GNOME.
#
# $POM_ID is the ID of the pomodoro that just ended. It is set by the caller.
#
terminal-notifier-success -message "Pomodoro $POM_ID started." > /dev/null
