#!/bin/sh

#
# Sample after-start-pomodoro hook for Paradeiser (called after a pomodoro started). It
# displays a simple notification.
#
# In order to use this hook, you'll have to chmod +x the hook in ~/paradeiser/hooks/*.
#
terminal-notifier-success -message "A new pomodoro started." > /dev/null
