#!/bin/sh

#
# Sample after-start-break hook for Paradeiser (called after a break started). It
# displays a simple notification.
#
# In order to use this hook, you'll have to chmod +x the hook in ~/paradeiser/hooks/*.
#
terminal-notifier-success -message "A new break started." > /dev/null
