#!/bin/sh

#
# Sample post-finish hook for Paradeiser (called after a pomodoro started). It
# displays a simple notification.
#
terminal-notifier-success -message "A new Pomodoro started." > /dev/null
