#!/bin/sh

#
# Sample after-start-pomodoro hook for Paradeiser (called after a pomodoro started). It
# displays a simple notification.
#
terminal-notifier-success -message "A new pomodoro started." > /dev/null
