#!/bin/bash

hooks=(
  "after-finish-break"
  "after-finish-pomodoro"
  "after-start-break"
  "after-start-pomodoro"
  "before-finish-break"
  "before-finish-pomodoro"
  "before-start-break"
  "before-start-pomodoro")

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

for hook in ${hooks[*]}; do
  ln -s "$DIR/fail" "$HOME/.paradeiser/hooks/$hook"
done
