#!/bin/sh

#
# Sample after-start-pomodoro hook for Paradeiser (called after a pomodoro started). It
# displays a simple notification.
#
notify-send "Pomodoro" "A new pomodoro started." -u critical > /dev/null
