#!/bin/sh

#
# Sample post-finish hook for Paradeiser (called after a pomodoro started). It
# displays a simple notification.
#
notify-send "Pomodoro" "A new Pomodoro started." -u critical > /dev/null
