#!/bin/sh

#
# Sample after-start-break hook for Paradeiser (called after a break started). It
# displays a simple notification.
#
notify-send "Pomodoro" "A new break started." -u critical > /dev/null
